# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AIHelpSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AIHelpSDKDemo
  pod 'AIHelpSDK', '~> 3.1.0'
  pod 'MBProgressHUD', '~> 1.2.0'

end
